--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 11.2

\c jeopardy

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET xmloption = content;
SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: answered_clues; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.answered_clues (
    id integer NOT NULL,
    played_game_id integer NOT NULL,
    clue_id integer NOT NULL,
    answered_correctly boolean NOT NULL,
    date_answered timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.answered_clues OWNER TO postgres;

--
-- Name: answered_clues_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.answered_clues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answered_clues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: played_games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.played_games (
    id integer NOT NULL,
    game_id integer NOT NULL,
    game_date date NOT NULL,
    date_played timestamp without time zone DEFAULT now() NOT NULL,
    round1_correct integer DEFAULT 0,
    round1_incorrect integer DEFAULT 0,
    round1_skipped integer DEFAULT 0,
    round2_correct integer DEFAULT 0,
    round2_incorrect integer DEFAULT 0,
    round2_skipped integer DEFAULT 0,
    coryat_score_round1 integer DEFAULT 0,
    coryat_score_round2 integer DEFAULT 0,
    coryat_score_total integer DEFAULT 0,
    completed boolean DEFAULT false,
    final_correct boolean DEFAULT false NOT NULL
);


ALTER TABLE public.played_games OWNER TO postgres;

--
-- Name: COLUMN played_games.final_correct; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.played_games.final_correct IS 'boolean field indicating if final jeopardy clue was answered correctly or not';


--
-- Name: played_games_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.played_games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.played_games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: answered_clues_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.answered_clues_id_seq', 88, true);

--
-- Name: played_games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.played_games_id_seq', 17, true);

--
-- Name: answered_clues answered_clues_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answered_clues
    ADD CONSTRAINT answered_clues_pkey PRIMARY KEY (id);


--
-- Name: played_games played_games_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.played_games
    ADD CONSTRAINT played_games_pkey PRIMARY KEY (id);


--
-- Name: played_games unique_game_date; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.played_games
    ADD CONSTRAINT unique_game_date UNIQUE (game_id, date_played);


--
-- Name: answered_clues unique_played_game_clue; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answered_clues
    ADD CONSTRAINT unique_played_game_clue UNIQUE (played_game_id, clue_id);

--
-- Name: answered_clues answered_clues_clue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answered_clues
    ADD CONSTRAINT answered_clues_clue_id_fkey FOREIGN KEY (clue_id) REFERENCES public.clues(id);


--
-- Name: answered_clues answered_clues_played_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answered_clues
    ADD CONSTRAINT answered_clues_played_game_id_fkey FOREIGN KEY (played_game_id) REFERENCES public.played_games(id);

--
-- PostgreSQL database dump complete
--

